wandb_version: 1

layer_1:
  desc: null
  value: 32
activation_1:
  desc: null
  value: relu
layer_2:
  desc: null
  value: 64
activation_2:
  desc: null
  value: relu
layer_3:
  desc: null
  value: 64
activation_3:
  desc: null
  value: relu
layer_4:
  desc: null
  value: 64
activation_4:
  desc: null
  value: relu
layer_5:
  desc: null
  value: 64
activation_5:
  desc: null
  value: relu
layer_6:
  desc: null
  value: 64
activation_6:
  desc: null
  value: relu
kernel_size:
  desc: null
  value:
  - 3
  - 3
pool_size:
  desc: null
  value:
  - 2
  - 2
n_dense_1:
  desc: null
  value: 64
activation_ndense_1:
  desc: null
  value: relu
n_dense_2:
  desc: null
  value: 4
activation_ndense_2:
  desc: null
  value: softmax
image_size:
  desc: null
  value: 256
optimizer:
  desc: null
  value: adam
loss:
  desc: null
  value: sparse_categorical_crossentropy
metrics:
  desc: null
  value: accuracy
epochs:
  desc: null
  value: 36
batch_size:
  desc: null
  value: 32
steps_per_epoch:
  desc: null
  value: 92
validation_steps:
  desc: null
  value: 22
verbose:
  desc: null
  value: 1
use_multiprocessing:
  desc: null
  value: true
workers:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704647359.933766
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      - 105
      2:
      - 2
      - 3
      - 12
      - 55
      - 105
      3:
      - 2
      - 3
      - 7
      - 8
      - 16
      - 23
      - 38
      - 39
      4: 3.10.13
      5: 0.16.1
      8:
      - 1
      - 5
      10:
      - 9
      13: linux-x86_64
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
